### ISSUE TITLE
Illegal number syntax on testing

### ISSUE THREAD

**Issue by traetox** [abligh/gonbdserver#1]
I am getting a panic on the golang test cases.

The output when running go test -v ./... is as follows:

?       _/tmp/gonbdserver       [no test files]
--- FAIL: TestConnection (0.00s)
panic: template: config:21: illegal number syntax: "-" [recovered]
        panic: template: config:21: illegal number syntax: "-"

goroutine 6 [running]:
testing.tRunner.func1(0xc82009e120)
        /usr/lib/go/src/testing/testing.go:450 +0x171
text/template.Must(0x0, 0x7f475bdae028, 0xc82000b520, 0x0)
        /usr/lib/go/src/text/template/helper.go:23 +0x4b
_/tmp/gonbdserver/nbd.StartNbd(0xc82009e120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/gonbdserver/nbd/nbd_test.go:101 +0xd97
_/tmp/gonbdserver/nbd.doTestConnection(0xc82009e120, 0xc80e7d4400)
        /tmp/gonbdserver/nbd/nbd_test.go:443 +0x7e
_/tmp/gonbdserver/nbd.TestConnection(0xc82009e120)
        /tmp/gonbdserver/nbd/nbd_test.go:459 +0x26
testing.tRunner(0xc82009e120, 0xe6c460)
        /usr/lib/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
        /usr/lib/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x8bf418, 0xe6c460, 0xa, 0xa, 0x1)
        /usr/lib/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc82009dee8, 0x7f475bdb2298)
        /usr/lib/go/src/testing/testing.go:494 +0x70
main.main()
        _/tmp/gonbdserver/nbd/_test/_testmain.go:72 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
FAIL    _/tmp/gonbdserver/nbd   0.046s

-------- END OF OUTPUT -------

I am running on a fully updated ubuntu 15.10 box with golang version 1.5.1

**Comment by abligh** [comment]
I think I saw that on go 1.4. You might want to try updating to go 1.6. The proper solution would be for me to make the test template back compatible. A patch is welcome (it's late here).

**Comment by traetox** [comment]
i will retest on 1.6.2 and look into rolling a patch that makes it
backwards compatible.  I may use the issue train to document some things as
I go for my own sake.  So ignore the notifications, get some sleep :)

On Fri, Apr 22, 2016 at 5:46 PM, Alex Bligh notifications@github.com
wrote:

> I think I saw that on go 1.4. You might want to try updating to go 1.6.
> The proper solution would be for me to make the test template back
> compatible. A patch is welcome (it's late here).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/abligh/gonbdserver/issues/1#issuecomment-213628222

## 

:ZZ

**Comment by abligh** [comment]
Fixed by e46ba8725f4e672f4d9da18fd6250322dbe89d32 (hopefully)
