### ISSUE TITLE
Rationale for custom allocator?

### ISSUE THREAD

**Issue by andrewchambers** [abligh/gonbdserver#12]
I can see this project was written a while ago, I wonder if the go garbage collector matured enough since then that this code is no longer necessary. 

I wonder what the authors opinions on that are.

**Comment by andrewchambers** [comment]
Oh, could it be to keep the buffers alive for cgo? Not sure.

**Comment by abligh** [comment]
This should be relatively easy to test. Without it there was a very substantial problem with memory consumption and a (probably related) issue with performance simply running the tests. Feel free to rip it out and try without. I don't believe it's necessary for the cgo stuff.

**Comment by andrewchambers** [comment]
Cool thanks for the answer :)
